#!/usr/bin/env python3
"""
Ticketing system integration — Jira, GitHub Issues, Linear.
Creates issues from Nuclei findings automatically.
"""

import requests
import json
import base64
from core.logger import get_logger

log = get_logger("Ticketing")


class TicketingModule:
    def __init__(self, cfg):
        self.cfg   = cfg
        self.creds = cfg.get("credentials") or {}

    def create_tickets(self, findings: list, domain: str) -> dict:
        """Create tickets for high/critical findings."""
        created = {"jira": [], "github": []}
        high_findings = [f for f in findings
                         if f.get("severity", "").lower() in ("critical", "high")]

        if not high_findings:
            log.info("[Ticketing] No high/critical findings to ticket")
            return created

        jira_cfg  = self.creds.get("jira", {})
        gh_cfg    = self.creds.get("github", {})

        for finding in high_findings:
            title = f"[Shaheen3] {finding.get('severity','').upper()}: {finding.get('name','')} on {domain}"
            body  = self._format_body(finding, domain)

            if jira_cfg.get("url") and jira_cfg.get("token"):
                ticket = self._create_jira(title, body, finding, jira_cfg)
                if ticket:
                    created["jira"].append(ticket)

            if gh_cfg.get("token") and gh_cfg.get("repo"):
                issue = self._create_github_issue(title, body, finding, gh_cfg)
                if issue:
                    created["github"].append(issue)

        log.info(f"[Ticketing] Created: {len(created['jira'])} Jira, {len(created['github'])} GitHub issues")
        return created

    def _format_body(self, finding: dict, domain: str) -> str:
        return f"""## Security Finding — {finding.get('name', '')}

**Severity:** {finding.get('severity', '').upper()}
**Target:** {domain}
**Matched URL:** {finding.get('matched', '')}
**Template:** {finding.get('template', '')}
**CVE:** {', '.join(finding.get('cve', [])) or 'N/A'}

### Description
{finding.get('description', 'No description available.')}

### References
{chr(10).join(finding.get('reference', [])) or 'None'}

---
*Auto-generated by Shaheen 3 v1.0 — Professor Snape*
"""

    def _create_jira(self, title: str, body: str, finding: dict, cfg: dict) -> dict:
        priority_map = {"critical": "Highest", "high": "High",
                        "medium": "Medium", "low": "Low"}
        sev      = finding.get("severity", "medium").lower()
        payload  = {
            "fields": {
                "project":     {"key": cfg.get("project", "SEC")},
                "summary":     title[:255],
                "description": body,
                "issuetype":   {"name": "Bug"},
                "priority":    {"name": priority_map.get(sev, "Medium")},
                "labels":      ["security", "shaheen3", "pentest"],
            }
        }
        auth = base64.b64encode(
            f"{cfg.get('email','')}:{cfg.get('token','')}".encode()
        ).decode()
        try:
            r = requests.post(
                f"{cfg.get('url')}/rest/api/3/issue",
                headers={"Authorization": f"Basic {auth}",
                         "Content-Type": "application/json"},
                json=payload, timeout=15,
            )
            if r.status_code in (200, 201):
                data = r.json()
                return {"id": data.get("key"), "url": f"{cfg.get('url')}/browse/{data.get('key')}"}
        except Exception as e:
            log.debug(f"  [Ticketing] Jira error: {e}")
        return {}

    def _create_github_issue(self, title: str, body: str, finding: dict, cfg: dict) -> dict:
        sev    = finding.get("severity", "medium").lower()
        labels = ["security", "shaheen3", sev]
        try:
            r = requests.post(
                f"https://api.github.com/repos/{cfg.get('repo')}/issues",
                headers={"Authorization": f"token {cfg.get('token')}",
                         "Accept": "application/vnd.github.v3+json"},
                json={"title": title, "body": body, "labels": labels},
                timeout=15,
            )
            if r.status_code in (200, 201):
                data = r.json()
                return {"id": data.get("number"), "url": data.get("html_url")}
        except Exception as e:
            log.debug(f"  [Ticketing] GitHub error: {e}")
        return {}
